# Generated by Django 2.0.6 on 2018-07-28 08:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('axfapp', '0006_foodtypes_goods'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('userAccount', models.CharField(max_length=20, primary_key=True, serialize=False, unique=True)),
                ('userPasswd', models.CharField(max_length=20)),
                ('userName', models.CharField(max_length=20)),
                ('userPhone', models.CharField(max_length=20)),
                ('userAdderss', models.CharField(max_length=100)),
                ('userImg', models.CharField(max_length=150)),
                ('userRank', models.IntegerField()),
                ('userToken', models.CharField(max_length=50)),
            ],
        ),
    ]
